language: node_js
node_js:
  - '8'
  - '9'
  - '10'

dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start